import axios from 'axios';
import prisma from '../lib/prisma';

export const createJiraTicket = async (userId: string, incidentId: string, summary: string) => {
  try {
    // 1. Get the user's Jira integration token and cloudId
    const integration = await prisma.integration.findUnique({
      where: { userId_provider: { userId, provider: 'JIRA' } }
    });

    if (!integration || !integration.accessToken) {
      console.log('No Jira integration found for user');
      return false;
    }

    const cloudId = (integration.metadata as any)?.cloudId;
    if (!cloudId) {
      console.log('No Jira cloudId found for user');
      return false;
    }

    let accessToken = integration.accessToken;

    const executeJiraLogic = async (token: string) => {
      // 2. Fetch incident details for context
      const incident = await prisma.incident.findUnique({
        where: { id: incidentId },
        select: { title: true, roomCode: true, severity: true }
      });

      if (!incident) return false;

      // 3. Fetch user's Jira projects to get a valid project key
      const projectsResponse = await axios.get(
        `https://api.atlassian.com/ex/jira/${cloudId}/rest/api/2/project`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: 'application/json'
          }
        }
      );

      if (!projectsResponse.data || projectsResponse.data.length === 0) {
        console.log('No Jira projects found for this user/site');
        return false;
      }

      const projectKey = projectsResponse.data[0].key;

      // Fetch issue types
      const projectMetadataResponse = await axios.get(
        `https://api.atlassian.com/ex/jira/${cloudId}/rest/api/2/project/${projectKey}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: 'application/json'
          }
        }
      );

      const issueTypes = projectMetadataResponse.data.issueTypes;
      if (!issueTypes || issueTypes.length === 0) {
        console.log('No issue types found for Jira project');
        return false;
      }

      const taskType = issueTypes.find((it: any) => it.name === "Task" && !it.subtask) 
        || issueTypes.find((it: any) => !it.subtask) 
        || issueTypes[0];

      // 4. Create the Jira issue
      const rawText = `*Incident:* ${incident.title}\n*Severity:* ${incident.severity}\n*Room Code:* ${incident.roomCode}\n\n*Resolution Summary:*\n${summary}\n\n_Auto-generated by OpsEcho AI Commander_`;
      
      const adfDescription = {
        version: 1,
        type: "doc",
        content: rawText.split('\n').map(line => ({
          type: "paragraph",
          content: line ? [{ type: "text", text: line }] : []
        }))
      };

      const issuePayload = {
        fields: {
          project: {
            key: projectKey
          },
          summary: `[OpsEcho] ${incident.title} (${incident.roomCode})`,
          description: adfDescription,
          issuetype: {
            id: taskType.id
          }
        }
      };

      const createResponse = await axios.post(
        `https://api.atlassian.com/ex/jira/${cloudId}/rest/api/3/issue`,
        issuePayload,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json'
          }
        }
      );

      console.log(`Successfully created Jira ticket ${createResponse.data.key} for incident ${incident.roomCode}`);
      return createResponse.data.key;
    };

    try {
      return await executeJiraLogic(accessToken);
    } catch (err: any) {
      if (err.response?.status === 401 && integration.refreshToken) {
        console.log("Jira token expired, attempting to refresh...");
        // Refresh token
        const refreshResponse = await axios.post('https://auth.atlassian.com/oauth/token', {
          grant_type: 'refresh_token',
          client_id: process.env.JIRA_CLIENT_ID?.trim(),
          client_secret: process.env.JIRA_CLIENT_SECRET?.trim(),
          refresh_token: integration.refreshToken
        });

        const newAccessToken = refreshResponse.data.access_token;
        const newRefreshToken = refreshResponse.data.refresh_token;

        await prisma.integration.update({
          where: { id: integration.id },
          data: {
            accessToken: newAccessToken,
            refreshToken: newRefreshToken
          }
        });

        console.log("Jira token refreshed successfully. Retrying request...");
        return await executeJiraLogic(newAccessToken);
      }
      throw err;
    }
  } catch (error: any) {
    const errorDetails = error?.response?.data || error.message;
    console.error('Failed to create Jira ticket:', errorDetails);
    throw new Error(JSON.stringify(errorDetails));
  }
};
