import axios from 'axios';
import prisma from '../lib/prisma';

export const createJiraTicket = async (userId: string, incidentId: string, summary: string) => {
  try {
    // 1. Get the user's Jira integration token and cloudId
    const integration = await prisma.integration.findUnique({
      where: { userId_provider: { userId, provider: 'JIRA' } }
    });

    if (!integration || !integration.accessToken) {
      console.log('No Jira integration found for user');
      return false;
    }

    const cloudId = (integration.metadata as any)?.cloudId;
    if (!cloudId) {
      console.log('No Jira cloudId found for user');
      return false;
    }

    // 2. Fetch incident details for context
    const incident = await prisma.incident.findUnique({
      where: { id: incidentId },
      select: { title: true, roomCode: true, severity: true }
    });

    if (!incident) return false;

    // 3. Fetch user's Jira projects to get a valid project key
    const projectsResponse = await axios.get(
      `https://api.atlassian.com/ex/jira/${cloudId}/rest/api/2/project`,
      {
        headers: {
          Authorization: `Bearer ${integration.accessToken}`,
          Accept: 'application/json'
        }
      }
    );

    if (!projectsResponse.data || projectsResponse.data.length === 0) {
      console.log('No Jira projects found for this user/site');
      return false;
    }

    const projectKey = projectsResponse.data[0].key; // Use the first available project

    // 4. Create the Jira issue (using API v2 to allow simple string descriptions)
    const issuePayload = {
      fields: {
        project: {
          key: projectKey
        },
        summary: `[OpsEcho] ${incident.title} (${incident.roomCode})`,
        description: `*Incident:* ${incident.title}\n*Severity:* ${incident.severity}\n*Room Code:* ${incident.roomCode}\n\n*Resolution Summary:*\n${summary}\n\n_Auto-generated by OpsEcho AI Commander_`,
        issuetype: {
          name: "Task" // "Task" or "Bug" usually exists. Task is standard.
        }
      }
    };

    const createResponse = await axios.post(
      `https://api.atlassian.com/ex/jira/${cloudId}/rest/api/2/issue`,
      issuePayload,
      {
        headers: {
          Authorization: `Bearer ${integration.accessToken}`,
          'Content-Type': 'application/json'
        }
      }
    );

    console.log(`Successfully created Jira ticket ${createResponse.data.key} for incident ${incident.roomCode}`);
    return createResponse.data.key;
  } catch (error: any) {
    console.error('Failed to create Jira ticket:', error?.response?.data || error.message);
    // If "Task" issue type doesn't exist, it might fail. For a robust integration, 
    // we would fetch issue types for the project first.
    return false;
  }
};
